cfg = {}


cfg.metric = true --// IF METRIC = TRUE THEN IT WILL SHOW AS KM/H, IF METRIC = FALSE, THEN IT WILL CHANGE TO MPH
cfg.radargun = "WEAPON_VINTAGEPISTOL"
cfg.marker = true --// IF TRUE == TRUE THEN IT WILL DRAW A MARKER ABOVE THE VEHICLE YOU ARE POINTING AT (https://gyazo.com/1d241fa6025a38a728af448ffd86b041)